server:
  port: 8081
spring:
  application:
    name: configserver
  profiles:
    active: native  #从本地读取
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared